const mongoose = require("mongoose");

const userSchema = mongoose.Schema({
    //id will be generated by mongoDB
  room: { type: String, default: "null", required: false },
  name: { type: String, default: "null", required: false },
  numVotes: { type: Number, default: 3, required: false },
  numVetos: { type: Number, default: 1, required: false },
  suggestion: { type: String, default: "null", required: false }
  
});

module.exports = mongoose.model("User", userSchema);